### PR TITLE
Added option to format the image url

### PR DESCRIPTION
**Pull request by kaareal**
@Juice10  @drakonen

### CODE REVIEW

**Comment by drakonen** [comment]
Why did you do it via settings? 
I also think the option should be called formatter instead of format.

**Comment by kaareal** [comment]
Because its global, wasn't sure how to get into the dimension, without making it global. 
I will fix the naming

I tried to fix up the table, but that didn't seems like an option, without major refactor.
So this seems the least harmful.

**Comment by drakonen** [comment]
:+1: :hamburger:

**Comment by Juice10** [comment]
should we put `// deprecated` above it?

**Comment by Juice10** [comment]
:+1:

**Pull request merged**
