### PR TITLE
Add ability to do value mappings to Table

### PR DESCRIPTION
**Pull request by kevinvandijk**
See the added example where the table is listing entityTypes, but the values of those need to be converted to some more user-friendly names when displaying them in the table.

I'm not too sure about the valueMapping name, does anyone have a better name?

/cc @drakonen @Juice10

### CODE REVIEW

**Comment by Juice10** [comment]
Maybe something like `valueLabels`

**Comment by Juice10** [comment]
This and #5 conflicts, so whatever goes in second needs to update the examples code as to not reference the same dom element, aka. `$(".widget7")`

**Comment by drakonen** [comment]
@kevinvandijk when you merge in master now, you'll find the new examples method.

**Comment by kevinvandijk** [comment]
Thanks@drakonen! I updated the example code and renamed it to `valueLabels`.

**Comment by drakonen** [comment]
:+1:

**Pull request merged**
